stages:
  - build
  - deploy

variables:
  GOFLAGS: -mod=readonly
  DOCKER_IMAGE_NAME: ${REGISTRY_HOST}/${CI_PROJECT_PATH}
  TARGET_DIR: ${PROJECT_DIR}/${CI_COMMIT_TAG}/${CI_PROJECT_NAME}

Build Images:
  stage: build
  image: docker:stable
  only:
    - tags
  tags:
    - bash
    - docker
  services:
    - docker:dind
  script:
    - docker build -t ${DOCKER_IMAGE_NAME}:${CI_COMMIT_TAG} .
    - docker login -u gitlab-ci-token -p ${OAUTH_ACCTOKEN} ${REGISTRY_HOST}
    - docker push ${DOCKER_IMAGE_NAME}:${CI_COMMIT_TAG}
